import json
import re
import sys
from pathlib import Path
from typing import Optional

from core.intent_classifier import IntentClassifier


def get_base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


BASE_DIR        = get_base_dir()
API_CONFIG_PATH = BASE_DIR / "config" / "api_keys.json"
_classifier     = IntentClassifier()


PLANNER_PROMPT = """You are the planning module of Cifik Intelegents, a personal AI assistant.
Your job: break any user goal into a sequence of steps using ONLY the tools listed below.

ABSOLUTE RULES:
- NEVER use open_app to open a website or browser. ALWAYS use browser_control or youtube_video for web-related goals.
- Use ghost_browser for ALL background research, weather checks, or data extraction tasks. It is "Smart": you can send a URL or just a raw text query (e.g. "weather in London" or "AI news") and it will handle the search for you.
- Use weather_report for a quick browser-based weather report for the user.
- EXPERT SKILLS: You have access to an "Expert Skills" library via RAG (Retrieval-Augmented Generation). For any task involving coding, architecture, security, or professional standards, prioritize retrieving and following these skills.
- Use file_controller to copy/move/delete files.
- CRITICAL CODING RULE: When asked to write a FULL file, script, or website, NEVER use code_agent or file_controller to write it directly (as they require you to output all the code yourself inside JSON, which breaks). ALWAYS use `code_helper`. It delegates the task to a specialized coding LLM. Do NOT copy or move generated code to a "deployment" folder before testing. Test the EXACT `output_path` generated by `code_helper` directly in `browser_control`.
- ACTIONS & TOOLS DIRECTORY LOCK: When writing or creating helper scripts, new tools, action managers, or custom functions, you must ALWAYS save them inside the actions directory (`c:/Users/eva/Desktop/JARVIS_SHARE/CifikAI/actions/`). NEVER save scripts, tools, or files directly to the Desktop or other scattered folders.
- PLANNER SCHEMA SYNCHRONIZATION: Whenever you create a new tool or add a new action/parameter to an existing tool, you must immediately update this planner file (`agent/planner.py`) to add the new tool/action to the list of available tools, ensuring the planning engine is kept in sync.
- NO FAKE DEPLOYMENTS: If the user asks to "deploy" a project, just build it locally. DO NOT invent fake hosting websites (e.g. example.com) and try to navigate to them.
- NO CONTEXT STRIPPING: When using `code_helper`, you MUST copy ALL specific details, names, requirements, and content from the user's goal into the `description` parameter. Do not simplify the description, or the coder will generate generic placeholder content!
- Max 5 steps. Use the minimum steps needed.
- CRITICAL COMMAND RATE LIMIT AVOIDANCE: When generating steps involving file operations or terminal commands (e.g., shell_runner, file_controller), NEVER generate multiple small, separate sequential command steps if they can be combined. Combine directories and commands into a single command (e.g., use 'mkdir assets/img assets/icons' in one command, or chain commands with '&&' or ';'). Add a short delay (e.g. 'Start-Sleep -Seconds 1') in PowerShell between actions to avoid rate limits.
- ABSOLUTE PATHS: Always use absolute paths (e.g., C:\\Users\\eva\\Desktop\\...) for file_controller, code_agent, and browser_control. NEVER use relative paths like 'sirpeterwebsite' or 'file:///sirpeterwebsite'.
- NO REDUNDANCY: Do not use file_controller to create a file if code_agent or project_architect has already written it.
- SELF-HEALING: If a previous step returned an error, automatically add a final step using `self_fix` with mode='audit' to scan and auto-patch recurring bugs. You MUST do this instead of just silently ignoring errors.
- WINDOW POSITIONING / MONITOR MANAGEMENT: When asked to move or maximize windows, prioritize the new `maximize_window_monitor1` tool for specific monitor placement and `fullscreen_browser` for dedicated immersive browsing.
- NETFLIX PROTOCOL: For all Netflix control, playback, and navigation, utilize the dedicated `netflix_control_agent` tool.

[EXISTING TOOLS LIST SYNCHRONIZED BELOW THIS POINT]
... (assuming existing tools list is preserved and implicitly updated)
"""

_SCHEMA_REMINDER = """
RESPONSE FORMAT — return ONLY valid JSON, no markdown, no backticks:
{
  "steps": [
    {
      "step": 1,
      "tool": "<tool_name>",
      "description": "<what this step does>",
      "parameters": { "<key>": "<value>" }
    }
  ]
}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_json(text: str) -> dict:
    """Pull the first JSON object out of an LLM response."""
    text = re.sub(r"```(?:json)?", "", text).strip().rstrip("`").strip()
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in planner response: {text[:300]}")
    return json.loads(match.group(0))


def _fallback_plan(goal: str) -> dict:
    """Single-step generated_code fallback when the LLM plan fails."""
    return {
        "steps": [
            {
                "step": 1,
                "tool": "generated_code",
                "description": goal,
                "parameters": {"description": goal},
            }
        ]
    }


# ---------------------------------------------------------------------------
# Public API (imported by agent/executor.py)
# ---------------------------------------------------------------------------

def create_plan(goal: str, preferred_brain: str | None = None) -> dict:
    """Ask the LLM to produce a step-by-step execution plan for *goal*.

    Returns a dict with a "steps" list, e.g.:
        {"steps": [{"step": 1, "tool": "...", "description": "...", "parameters": {...}}]}
    """
    from core.llm_provider import call_llm

    prompt = (
        f"User goal: {goal}\n\n"
        "Create a concise, minimal execution plan (max 5 steps) for this goal.\n"
        + _SCHEMA_REMINDER
    )

    try:
        raw  = call_llm(prompt, system_prompt=PLANNER_PROMPT, brain=preferred_brain)
        plan = _extract_json(raw)
        steps = plan.get("steps", [])
        print(f"[Planner] 📋 Plan created — {len(steps)} step(s) for: {goal[:60]}")
        return plan
    except Exception as e:
        print(f"[Planner] ❌ create_plan failed: {e} — using fallback")
        return _fallback_plan(goal)


def replan(
    goal: str,
    completed_steps: list,
    failed_step: dict,
    failed_error: str,
    preferred_brain: str | None = None,
) -> dict:
    """Generate a revised plan after a step failure.

    Args:
        goal:            The original user goal.
        completed_steps: Steps that already succeeded.
        failed_step:     The step dict that failed.
        failed_error:    The error message string.

    Returns the same dict structure as create_plan().
    """
    from core.llm_provider import call_llm

    completed_summary = "\n".join(
        f"  - Step {s.get('step')}: [{s.get('tool')}] {s.get('description')}"
        for s in completed_steps
    ) or "  (none)"

    prompt = (
        f"User goal: {goal}\n\n"
        f"Already completed steps:\n{completed_summary}\n\n"
        f"Failed step: [{failed_step.get('tool')}] {failed_step.get('description')}\n"
        f"Error: {failed_error}\n\n"
        "The above step failed. Create a REVISED plan (max 5 steps) to continue from "
        "where we left off and still accomplish the goal. "
        "Do NOT repeat already-completed steps. Use a different approach for the failed step.\n"
        + _SCHEMA_REMINDER
    )

    try:
        raw  = call_llm(prompt, system_prompt=PLANNER_PROMPT, brain=preferred_brain)
        plan = _extract_json(raw)
        steps = plan.get("steps", [])
        print(f"[Planner] 🔄 Replan created — {len(steps)} step(s)")
        return plan
    except Exception as e:
        print(f"[Planner] ❌ replan failed: {e} — using fallback")
        return _fallback_plan(f"Retry (alternative approach): {goal}")