# JARVIS Autonomous Project Architect
import os
import json
from pathlib import Path

class ProjectArchitect:
    def __init__(self, player=None):
        self.player = player
        self.base_dir = Path.home() / "Desktop" / "JARVIS_PROJECTS"
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def scaffold(self, name, description, tech_stack="python"):
        """Generates a full project structure based on description."""
        project_path = self.base_dir / name
        if project_path.exists():
            return {"status": "error", "message": f"Project '{name}' already exists, sir."}
        
        project_path.mkdir(parents=True)
        
        print(f"[Architect] 🏗️ Drafting blueprint for '{name}'...")
        if self.player: self.player.write_log(f"🏗️ Architect: Drafting blueprint for {name}...")

        # Here we would normally call the LLM to get a JSON blueprint
        # For now, we will create a standard robust structure based on tech_stack
        # and leave the "Genius" part to the Planner who calls this.
        
        blueprint = self._generate_standard_blueprint(name, description, tech_stack)
        
        created_files = []
        for item in blueprint:
            p = project_path / item["path"]
            p.parent.mkdir(parents=True, exist_ok=True)
            with open(p, "w", encoding="utf-8") as f:
                f.write(item["content"])
            created_files.append(item["path"])
            
        # Git Init
        import subprocess
        try:
            subprocess.run(["git", "init"], cwd=str(project_path), capture_output=True)
            subprocess.run(["git", "add", "."], cwd=str(project_path), capture_output=True)
            subprocess.run(["git", "commit", "-m", "Genesis Commit (scaffolded by JARVIS Architect)"], cwd=str(project_path), capture_output=True)
            git_status = "and initialized with Git."
        except:
            git_status = "but Git initialization failed."

        return {
            "status": "success",
            "message": f"Project '{name}' scaffolded at {project_path} {git_status}",
            "files": created_files
        }

    def _generate_standard_blueprint(self, name, description, tech_stack):
        """Creates a professional-grade boilerplate blueprint."""
        blueprint = []
        
        if "python" in tech_stack.lower():
            blueprint = [
                {"path": "README.md", "content": f"# {name}\n\n{description}\n\nGenerated by JARVIS Architect."},
                {"path": "requirements.txt", "content": "requests\npython-dotenv\n"},
                {"path": "main.py", "content": f"\"\"\"\n{name} - Main Entry Point\n\"\"\"\ndef main():\n    print('Hello from {name}!')\n\nif __name__ == '__main__':\n    main()"},
                {"path": "core/__init__.py", "content": ""},
                {"path": "utils/__init__.py", "content": ""},
                {"path": ".env", "content": "# Environment Variables\n"},
                {"path": ".gitignore", "content": "__pycache__/\n.env\n*.pyc\nvenv/\n"}
            ]
        elif "web" in tech_stack.lower() or "js" in tech_stack.lower():
            blueprint = [
                {"path": "index.html", "content": f"<!DOCTYPE html>\n<html>\n<head>\n<title>{name}</title>\n<link rel='stylesheet' href='style.css'>\n</head>\n<body>\n<h1>{name}</h1>\n<script src='script.js'></script>\n</body>\n</html>"},
                {"path": "style.css", "content": "body { font-family: sans-serif; background: #121212; color: white; }"},
                {"path": "script.js", "content": f"console.log('{name} initialized.');"},
                {"path": "README.md", "content": f"# {name}\n\n{description}"}
            ]
            
        return blueprint

def project_architect(parameters, player=None):
    name = parameters.get("name", "NewProject")
    desc = parameters.get("description", "A new JARVIS project.")
    tech = parameters.get("tech_stack", "python")
    
    architect = ProjectArchitect(player)
    return architect.scaffold(name, desc, tech)
